name: Deploy to Github Pages on Pull request or Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Static Webite
        run: |
          mkdir static
          cp index.html static

      - name: Upload Static Pages as Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: static/

      - name: Deploy Artifact for GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ github.token }}
          artifact_name: github-pages
